---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip-bot-cs-sc-bridge-jupyter
  labels:
    app: zulip-bot-cs-sc-bridge-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zulip-bot-cs-sc-bridge-jupyter
  template:
    metadata:
      labels:
        app:
          zulip-bot-cs-sc-bridge-jupyter
    spec:
      automountServiceAccountToken: false
      containers:
        - name: bot
          image: aaltoscienceit/zulip-bot:0.1.0
          command:
            - python
            - /python-zulip-api/zulip/integrations/bridge_between_zulips/run-interrealm-bridge
            - --stream
          volumeMounts:
            - name: zulip-bridge-config-cs-sc-jupyter
              mountPath: /python-zulip-api/zulip/integrations/bridge_between_zulips/interrealm_bridge_config.py
              subPath: interrealm_bridge_config
              readOnly: true
          #resources:
          #  limits:
          #    memory: 100M
          #    cpu: .1
          #  requests: ...
          #env:
          #  - name: ...
          #    value: ...
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: zulip-bridge-config-cs-sc-jupyter
          secret:
            secretName: zulip-cs-sc-bridge-jupyter
